version: "2.0"
services:
  mqtt:
    image: mjenz/rpi-mosquitto
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ./config/mqtt:/mqtt/config:ro
      - /home/pi/Volumes/mqtt/data:/mqtt/data
      - /home/pi/Volumes/mqtt/log:/mqtt/log
    network_mode: "host"
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8070:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyAMA0:/dev/ttyAMA0
    restart: unless-stopped
    privileged: true
