version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./config:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
      - 18080:8080
    command: "mosquitto -c /mosquitto-no-auth.conf"
