version: "3"
services:
  telegraf:
    image: telegraf:1.16
    container_name: telegraf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        #ports:
        #- 8092:8092/udp
        #- 8094:8094
        #- 8125:8125/udp
    network_mode: "host"
  chronograf:
    image: chronograf:latest
    ports:
      - "127.0.0.1:8890:8888"
    volumes:
      - /home/pi/Volumes/chronograf:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
  promtail:
    #image: grafana/promtail:2.0.0
    image: grafana/promtail:latest
    restart: always
    volumes:
      - ./config:/etc/promtail
      - /etc/promtail/promtail-targets.yaml:/etc/promtail/promtail-targets.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/hosts:/etc/hosts:ro
    command: -config.file=/etc/promtail/promtail.yaml
    network_mode: host
    privileged: true
  pushgateway:
    image: prom/pushgateway:v1.0.1
    restart: always
    command:
      - --persistence.file=/data/pushgateway.data
      - --persistence.interval=1h
    expose:
      - 9091
    ports:
      - 9091:9091
    volumes:
      - /home/pi/Volumes/pushgateway:/data
