version: "2.0"
services:
  home-assistant:
    #image: homeassistant/raspberrypi3-homeassistant:stable
    #image: homeassistant/home-assistant
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: home-assistant
    restart: always
    volumes:
      - /home/pi/Projects/home-assistant/config:/config
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime:ro
      # Bluetooth
      - /run/dbus:/run/dbus:ro
    network_mode: "host"
    environment:
      - TZ=America/Chicago
    # NOTE: could these device files change?
    devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0
      #- /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300853-if00-port0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300853-if01-port0:/dev/ttyUSB1
      #- /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2692360-if00:/dev/ttyUSB2
      # TODO: figure out how to run as not-privileged: https://community.home-assistant.io/t/migration-to-2021-7-fails-fatal-python-error-init-interp-main-cant-initialize-time/320648/3
    privileged: true
    #cap_add:
    #  - CAP_SETFCAP
    #user: "911:911" # "${USER_UID}:{USER_GID}"
    deploy:
      resources:
        limits:
          cpus: "1.0" # CPU core
