homeassistant: true
permit_join: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.243:1883
serial:
  port: /dev/ttyACM0
  adapter: deconz
devices:
  '0xa4c1383205699ded':
    friendly_name: '0xa4c1383205699ded'
  '0x00158d000864f652':
    friendly_name: '0x00158d000864f652'
