version: "2"
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: mjenz/rpi-openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - ./conf:/etc/openvpn
