---
version: "2.1"
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "./config:/config"
    ports:
      - 3000:3000 #optional
    restart: unless-stopped