# NOTE: this needs to be copied to /etc/promtail/ for changes to take effect
#         - this is the directory which will be mounted by docker-compose

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://grafana:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/lib/docker/containers/*/*log
    file_sd_configs:
      - files:
        - /etc/promtail/promtail-targets.yaml
    relabel_configs:
      - source_labels: [__address__]
        target_label: container_id
      - source_labels: [container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1*/*.log
  - job_name: cron
    static_configs:
      - targets:
          - localhost
        labels:
          job: cron
          __path__: /home/pi/.cache/.workflow/*log


