- description: "switch-toggle-frontyard-hose"
  id: "1248226327456"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 5ce89c45457b99a84eb2896c8d595f45
        endpoint_id: 3
        cluster_id: 6
        command: remote_button_short_press
        args: []
        params: {}
  condition: []
  action:
    - type: toggle
      device_id: c9323841349f7ac7a9bd159f757eb03c
      entity_id: switch.0xa4c1383205699ded
      domain: switch
  alias: Toggle Frontyard Hose
