- description: "switch-toggle-backyard-hose"
  id: "1638738317412"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 5ce89c45457b99a84eb2896c8d595f45
        endpoint_id: 2
        cluster_id: 6
        command: remote_button_short_press
        args: []
        params: {}
  condition: []
  action:
    - type: toggle
      device_id: 06475782fd1f328e27ecf05f945aec11
      entity_id: switch.backyard_hose_timer_zone
      domain: switch
  alias: Toggle Backyard Hose
