- id: "1633278418263"
  alias: switch-toggle-backyard-string-lights
  description: ""
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 5ce89c45457b99a84eb2896c8d595f45
        endpoint_id: 1
        cluster_id: 6
        command: remote_button_short_press
        args: []
        params: {}
  condition: []
  action:
    - service: switch.toggle
      target:
        entity_id: switch.smart_plug_6_switch
  mode: single
- id: "1633738838537"
  alias: sunset-turnon-backyard-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "0:15"
  condition: []
  action:
    - type: turn_on
      device_id: 2a10cb6b191cdb24c8c4336d441605df
      entity_id: switch.smart_plug_6_switch
      domain: switch
  mode: single
- id: "1633738917611"
  alias: sunset-plus5hr-turnoff-backyard-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "5:00"
  condition: []
  action:
    - type: turn_off
      device_id: 2a10cb6b191cdb24c8c4336d441605df
      entity_id: switch.smart_plug_6_switch
      domain: switch
  mode: single
