- id: "1677731437365"
  alias: turn-on-driveway-light-when-motion-detected
  description: ""
  trigger:
    # - type: occupied
    #   platform: device
    #   device_id: a2817b57b09fe69cf4fffdcc264c0e3e
    #   entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_2
    #   domain: binary_sensor
  
    - type: motion
      platform: device
      device_id: 11fb3d2922fb58e14230c471d871a1b0
      entity_id: binary_sensor.driveway_motion_sensor_occupancy
      domain: binary_sensor
  condition:
    - condition: sun
      before: sunrise
      after: sunset
  action:
    - type: turn_on
      device_id: 5c606aafc2ab973585cb0279d5e5a742
      entity_id: light.driveway_light
      domain: light
  mode: single
  # TODO: turn off after a certain point...

- id: "1677811291662"
  alias: turn-off-driveway-light-when-not-occupied
  description: ""
  trigger:
    # - type: not_occupied
    #   platform: device
    #   device_id: a2817b57b09fe69cf4fffdcc264c0e3e
    #   entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_2
    #   domain: binary_sensor
    - type: no_motion
      platform: device
      device_id: 11fb3d2922fb58e14230c471d871a1b0
      entity_id: binary_sensor.driveway_motion_sensor_occupancy
      domain: binary_sensor
  condition: []
  action:
    - type: turn_off
      device_id: 5c606aafc2ab973585cb0279d5e5a742
      entity_id: light.driveway_light
      domain: light
  mode: single
