- id: "1633278418263"
  alias: switch-toggle-backyard-string-lights
  description: ""
  trigger:
    - device_id: 5ce89c45457b99a84eb2896c8d595f45
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: button_1
  condition: []
  action:
    - type: toggle
      device_id: 2a10cb6b191cdb24c8c4336d441605df
      entity_id: switch.smart_plug_6_switch
      domain: switch
  mode: single
- id: "1633738838537"
  alias: sunset-turnon-backyard-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "0:15"
  condition: []
  action:
    - type: turn_on
      device_id: 2a10cb6b191cdb24c8c4336d441605df
      entity_id: switch.smart_plug_6_switch
      domain: switch
  mode: single
- id: "1633738917611"
  alias: sunset-plus5hr-turnoff-backyard-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "5:00"
  condition: []
  action:
    - type: turn_off
      device_id: 2a10cb6b191cdb24c8c4336d441605df
      entity_id: switch.smart_plug_6_switch
      domain: switch
  mode: single
