- id: "1639939566463"
  alias: button1-toggle-bedroom-string-lights
  description: ""
  trigger:
    - platform: device
      domain: mqtt
      device_id: 9e42f5feaa1144af146dd64ae7ee9900
      type: click
      subtype: single
    # - platform: event
    #   event_type: zha_event
    #   event_data:
    #     unique_id: 719637889f2498a3d70a1f7ea7f746e0
    #     command: button_single
  condition: []
  action:
    - type: toggle
      device_id: 73872a794dd14117d25788ab46f69543
      entity_id: switch.smart_plug_0
      domain: switch
  mode: single
