- id: "1677731437365"
  alias: turn-on-driveway-light-when-motion-detected
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.driveway_motion_sensor
      from: "off"
      to: "on"
    - platform: state
      entity_id: binary_sensor.driveway_motion_sensor_occupancy_1 # ZHA
      from: "off"
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion # mqtt
      from: "off"
      to: "on"
  condition:
    - condition: sun
      after: sunset
      before: sunrise
  action:
    - service: light.turn_on
      target:
        entity_id: light.driveway_light
- id: "1677811291662"
  alias: turn-off-driveway-light-when-not-occupied
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.driveway_motion_sensor
      from: "on"
      to: "off"
      for:
        minutes: 2   # ← highly recommended
  action:
    - service: light.turn_off
      target:
        entity_id: light.driveway_light
