- id: "1639939566463"
  alias: button1-toggle-bedroom-string-lights
  description: ""
  trigger:
    - device_id: 719637889f2498a3d70a1f7ea7f746e0
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition: []
  action:
    - type: toggle
      device_id: 1baf2d052ed2bb5e127c2969f0408d77
      entity_id: switch.smart_plug_0
      domain: switch
  mode: single
