- id: "1621329449658"
  alias: sunset-plus-7-turnoff-workbench-light
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "7:30"
  condition: []
  action:
    - type: turn_off
      device_id: 95a59e307bc74d56acce312f849753a1
      entity_id: switch.workbench_light_smart_plug_5_socket_1
      domain: switch
  mode: single

