- id: "1631321849219"
  alias: sunset-turnon-front-porch-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "1:30"
  condition: []
  action:
    - type: turn_on
      device_id: 00ab74d8c93098199435d24acf15961f
      entity_id: switch.christmas_lights_smart_plug_9_switch_2
      #entity_id: switch.0x00124b00226d64c4
      domain: switch
  mode: single
- id: "1631321965638"
  alias: sunset-plus6hr-turnoff-front-porch-string-lights
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 06:00:00
  condition: []
  action:
    - type: turn_off
      device_id: 00ab74d8c93098199435d24acf15961f
      entity_id: switch.christmas_lights_smart_plug_9_switch_2
      #entity_id: switch.christmas_lights
      domain: switch
  mode: single

#- alias: switch-toggle-front-porch-string-lights
#description: ""
#trigger:
#- device_id: 5ce89c45457b99a84eb2896c8d595f45
#  domain: zha
#  platform: device
#  type: remote_button_short_press
#  subtype: button_2
#condition: []
#action:
#- type: toggle 
#  device_id: 3b7129a1a791ca8dea5d00a2b1da6e45
#  #entity_id: switch.smart_plug_9_switch_2
#  entity_id: switch.christmas_lights
#  domain: switch
#mode: single
