- id: '1631075410449'
  alias: Toggle Office String Lights
  description: ''
  trigger:
  - device_id: 5ce89c45457b99a84eb2896c8d595f45
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  - platform: device
    type: turned_on
    device_id: ee36799d2ff31abb9a68f08334a0c53f
    entity_id: switch.tz3000_xabckq1v_ts004f_6a766bfe_on_off
    domain: switch
  condition: []
  action:
  - type: toggle
    device_id: 1baf2d052ed2bb5e127c2969f0408d77
    entity_id: switch.ewelink_sa_003_zigbee_6bf0d522_on_off
    domain: switch
  mode: single
- id: '1631076079215'
  alias: Toggle Living Room String Lights
  description: ''
  trigger:
  - device_id: 5ce89c45457b99a84eb2896c8d595f45
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_4
  condition: []
  action:
  - type: toggle
    device_id: c62836e61b52ccc9bab970cbec757d48
    entity_id: switch.eb9f88cafdc227b60ausoh
    domain: switch
  mode: single
- id: '1631321849219'
  alias: Turn on Front Porch Lights at Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1:30'
  condition: []
  action:
  - type: turn_on
    device_id: a5400ac0b2bd9a5e622e22c8514e6400
    entity_id: switch.ebaf14ce1e9dad603d4p5e
    domain: switch
  mode: single
- id: '1631321965638'
  alias: Turn off Front Porch Lights 4 Hours After Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 04:00:00
  condition: []
  action:
  - type: turn_off
    device_id: a5400ac0b2bd9a5e622e22c8514e6400
    entity_id: switch.ebaf14ce1e9dad603d4p5e
    domain: switch
  mode: single
- id: '1632251772271'
  alias: Toggle Office Lights
  description: ''
  trigger:
  - device_id: 9207a1c4c264befd7e62c32fee0e3155
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  - device_id: 719637889f2498a3d70a1f7ea7f746e0
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 2b76e34a8a2d43b790fb6b8d4fe03e13
    entity_id: light.hue_white_lamp_2
    domain: light
  - type: toggle
    device_id: 1baf2d052ed2bb5e127c2969f0408d77
    entity_id: switch.ewelink_sa_003_zigbee_6bf0d522_on_off
    domain: switch
  mode: single
- id: '1633229888079'
  alias: Toggle Front Porch String Lights
  description: ''
  trigger:
  - device_id: 5ce89c45457b99a84eb2896c8d595f45
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - type: toggle
    device_id: a5400ac0b2bd9a5e622e22c8514e6400
    entity_id: switch.ebaf14ce1e9dad603d4p5e
    domain: switch
  mode: single
- id: '1633278418263'
  alias: Toggle Backyard String Lights
  description: ''
  trigger:
  - device_id: 5ce89c45457b99a84eb2896c8d595f45
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 58ef53f173cdefd7bf3454144fbf275f
    entity_id: switch.ebb633cd9e5de587142f82
    domain: switch
  mode: single
- id: '1633481274356'
  alias: Turn on Living Room Lights at Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1:00'
  condition: []
  action:
  - type: turn_on
    device_id: c62836e61b52ccc9bab970cbec757d48
    entity_id: switch.eb9f88cafdc227b60ausoh
    domain: switch
  mode: single
- id: '1633481363918'
  alias: Turn off Living Room Lights 4 Hours aftet Sunset
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: c62836e61b52ccc9bab970cbec757d48
    entity_id: switch.eb9f88cafdc227b60ausoh
    domain: switch
  mode: single
- id: '1633738838537'
  alias: Turn on Backyard Lights after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '2:00'
  condition: []
  action:
  - type: turn_on
    device_id: 58ef53f173cdefd7bf3454144fbf275f
    entity_id: switch.ebb633cd9e5de587142f82
    domain: switch
  mode: single
- id: '1633738917611'
  alias: Turn off Backyard Lights 4 hours after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '4:00'
  condition: []
  action:
  - type: turn_off
    device_id: 58ef53f173cdefd7bf3454144fbf275f
    entity_id: switch.ebb633cd9e5de587142f82
    domain: switch
  mode: single
- id: '1633924922517'
  alias: Test
  description: ''
  trigger:
  - device_id: 719637889f2498a3d70a1f7ea7f746e0
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 1baf2d052ed2bb5e127c2969f0408d77
    entity_id: switch.ewelink_sa_003_zigbee_6bf0d522_on_off
    domain: switch
  mode: single
