- id: '1680368920618'
  alias: New Automation
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 0d442e3ede49b0055d2c85f1f52c2de5
    entity_id: light.smart_switch_guest_room_light
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: 0bc4918becee90ccc3a53630fdfc96e7
    entity_id: switch.tz3000_nfnmi125_ts011f_switch
    domain: switch
  mode: single
- id: '1680409115819'
  alias: New Automation
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 0d442e3ede49b0055d2c85f1f52c2de5
    entity_id: light.smart_switch_guest_room_light
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: 2b76e34a8a2d43b790fb6b8d4fe03e13
    entity_id: light.hue_white_lamp_2
    domain: light
  mode: single
