
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

ecovacs:
  username: !secret email
  password: !secret deebot_password
  country: us
  continent: na

pi_hole:
  - host: !secret pihole_host

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber_id

# ring
camera:
  - platform: ring
ring:
  username: !secret ring_username
  password: !secret ring_password

sensor:
  - platform: google_wifi
    name: "Google WiFi"
    host: 192.168.1.1
  - platform: ring
  - platform: template
    sensors:
      outdoor_temperature_f:
        friendly_name: "Outdoor Temperature F"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"


device_tracker:
  - platform: netgear
    host: 192.168.1.2
    port: 80
    username: !secret netgear_username
    password: !secret netgear_password
    accesspoints:
      - netgear
    
