# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  # mode: storage
  # Add yaml dashboards
  dashboards:
    ui-overview:
      mode: yaml
      title: System
      filename: ui-lovelace.yaml
      show_in_sidebar: false
    ui-mobile: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui-lovelace.mobile.yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
      require_admin: true

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

bluetooth:

# ecovacs:
#   username: !secret email
#   password: !secret deebot_password
#   country: us
#   continent: na

# pi_hole:
#   - host: !secret pihole_host

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber_id

camera:
  - platform: ffmpeg
    name: wyze_v3
    #input: rtsp://192.168.1.63:8554/video1
    input: !secret wb_rtsp_url_living_room_cam
  - platform: ffmpeg
    name: wyze_v3_garage_cam
    input: !secret wb_rtsp_url_garage_cam
  - platform: ffmpeg
    name: wyze_v3_driveway_cam
    input: rtsp://192.168.1.243:8554/driveway-cam
    #input: !secret wb_rtsp_url_driveway_cam
    # name: wyze_v3_driveway_cam
    # input: rtsp://192.168.1.55:8554/video1_unicast
  - platform: ffmpeg
    name: camera.front_door_1
    input: rtsp://192.168.1.243:8555
  - platform: ffmpeg
    name: wyze_og_bear_cam
    input: !secret wb_rtsp_url_bear_cam


sensor:
  - platform: google_wifi
    name: "Google WiFi"
    host: 192.168.1.1
  - platform: template
    sensors:
      outdoor_temperature_f:
        friendly_name: "Outdoor Temperature F"
        unit_of_measurement: "°F"
        value_template: "{{ state_attr('weather.home', 'temperature') }}"

#midea_dehumidifier:
#  username: sthinds144@gmail.com
#  password: !secret midea_password

device_tracker:
  - platform: netgear
    host: 192.168.1.2
    port: 80
    username: !secret netgear_username
    password: !secret netgear_password
    accesspoints:
      - netgear
# no longer configurable from YAML
#mqtt:
#  broker: 192.168.1.243
#  port: 1883
#  discovery: true
#  discovery_prefix: homeassistant
#  username: mosquitto
