
b8_27_eb_50_20_03:
  name: B8:27:EB:50:20:03
  mac: B8:27:EB:50:20:03
  icon:
  picture:
  track: true

unknown:
  name: UNKNOWN
  mac: 58:24:29:92:E2:A2
  icon:
  picture:
  track: true


b0_39_56_07_03_08:
  name: netgear
  mac: B0:39:56:07:03:08
  icon:
  picture:
  track: true

b8_27_eb_91_f3_77:
  name: B8:27:EB:91:F3:77
  mac: B8:27:EB:91:F3:77
  icon:
  picture:
  track: true

fe_3d_33_56_b7_ba:
  name: FE:3D:33:56:B7:BA
  mac: FE:3D:33:56:B7:BA
  icon:
  picture:
  track: true

84_f3_eb_5c_76_3e:
  name: 84:F3:EB:5C:76:3E
  mac: 84:F3:EB:5C:76:3E
  icon:
  picture:
  track: true

b8_27_eb_b3_aa_72:
  name: B8:27:EB:B3:AA:72
  mac: B8:27:EB:B3:AA:72
  icon:
  picture:
  track: true

70_89_76_19_de_e6:
  name: 70:89:76:19:DE:E6
  mac: 70:89:76:19:DE:E6
  icon:
  picture:
  track: true

02_19_11_d7_df_22:
  name: 02:19:11:D7:DF:22
  mac: 02:19:11:D7:DF:22
  icon:
  picture:
  track: true

64_07_f6_7f_0e_a4:
  name: 64:07:F6:7F:0E:A4
  mac: 64:07:F6:7F:0E:A4
  icon:
  picture:
  track: true

cc_a7_c1_15_a6_24:
  name: CC:A7:C1:15:A6:24
  mac: CC:A7:C1:15:A6:24
  icon:
  picture:
  track: true

58_24_29_92_e8_22:
  name: 58:24:29:92:E8:22
  mac: 58:24:29:92:E8:22
  icon:
  picture:
  track: true

70_89_76_3b_3b_f9:
  name: 70:89:76:3B:3B:F9
  mac: 70:89:76:3B:3B:F9
  icon:
  picture:
  track: true

d4_5d_64_d5_bc_84:
  name: D4:5D:64:D5:BC:84
  mac: D4:5D:64:D5:BC:84
  icon:
  picture:
  track: true

34_97_f6_59_1e_fe:
  name: 34:97:F6:59:1E:FE
  mac: 34:97:F6:59:1E:FE
  icon:
  picture:
  track: true

b8_27_eb_d5_25_78:
  name: B8:27:EB:D5:25:78
  mac: B8:27:EB:D5:25:78
  icon:
  picture:
  track: true

70_89_76_19_de_d5:
  name: 70:89:76:19:DE:D5
  mac: 70:89:76:19:DE:D5
  icon:
  picture:
  track: true

1e_53_30_6e_f1_15:
  name: 1E:53:30:6E:F1:15
  mac: 1E:53:30:6E:F1:15
  icon:
  picture:
  track: true

70_89_76_7e_93_a7:
  name: 70:89:76:7E:93:A7
  mac: 70:89:76:7E:93:A7
  icon:
  picture:
  track: true

48_b0_2d_37_cc_12:
  name: 48:B0:2D:37:CC:12
  mac: 48:B0:2D:37:CC:12
  icon:
  picture:
  track: true

ac_64_cf_6f_2b_4a:
  name: AC:64:CF:6F:2B:4A
  mac: AC:64:CF:6F:2B:4A
  icon:
  picture:
  track: true

34_9f_7b_7f_52_9a:
  name: 34:9F:7B:7F:52:9A
  mac: 34:9F:7B:7F:52:9A
  icon:
  picture:
  track: true

00_17_88_65_52_e3:
  name: 00:17:88:65:52:E3
  mac: 00:17:88:65:52:E3
  icon:
  picture:
  track: true
