title: Home
views:
  - panel: true
    badges:
      - entity: person.sean
      - entity: person.amy
      - entity: sun.sun
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: camera.front_door_mqtt
              - type: picture-entity
                entity: camera.wyze_v3_garage_cam
          - type: horizontal-stack
            cards:
              - camera_view: auto
                type: picture-glance
                title: Living Room
                image: https://demo.home-assistant.io/stub_config/kitchen.png
                entities:
                  - entity: camera.wyze_v3
                camera_image: camera.wyze_v3
              - type: picture-entity
                entity: camera.wyze_v3_driveway_cam
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: entities
                    title: Front Door
                    entities:
                      - binary_sensor.ding
                      - binary_sensor.motion
                      - button.take_snapshot
                  - type: entities
                    entities:
                      - binary_sensor.driveway_motion_sensor_occupancy
                      - sensor.driveway_motion_sensor_battery
                      - sensor.driveway_motion_sensor_illuminance_lux
                      - sensor.driveway_motion_sensor_device_temperature
                    title: Driveway Motion Sensor
                  - title: Front Gate
                    type: entities
                    entities:
                      - entity: binary_sensor.backyard_front_gate_sensor_contact
                        name: Front Gate Sensor Contact
                      - entity: binary_sensor.backyard_front_gate_sensor_battery_low
                        name: Front Gate Sensor Battery Low
                      - entity: sensor.backyard_front_gate_sensor_battery
                        name: Front Gate Sensor Battery
                  - title: Back Door
                    type: entities
                    entities:
                      - binary_sensor.back_door_sensor_contact
                      - sensor.back_door_sensor_battery
                      - sensor.back_door_sensor_device_temperature
                  - type: history-graph
                    entities:
                      - entity: binary_sensor.backyard_front_gate_sensor_contact
                        name: Front Gate
                      - entity: binary_sensor.back_door_sensor_contact
                        name: Back Door
              - type: entities
                entities:
                  - entity: light.hue_white_lamp_1
                    name: Philips Hue - Guest Room
                  - entity: switch.office_string_lights
                    name: Smart Plug - Office Lights
                  - entity: light.hue_white_lamp_2
                    name: Philips Hue - Office
                  - entity: switch.smart_plug_0
                    name: Bedroom String Lights
                  - entity: switch.smart_plug_6_switch
                    name: Backyard String Lights
                  - entity: light.guest_room_light_switch_light_2
                    name: Guestroom Lights
                  - entity: light.guest_room_light_switch_light
                    name: Guestroom Fan
                  #- entity: switch.smart_plug_9_switch_2
                  - entity: switch.smart_plug_5_socket_1
                    name: Garage Workbench Light
                  - entity: light.driveway_light
                    name: Driveway Light
                  - entity: switch.smart_plug_9
                    name: Christmas Lights
                  - entity: light.garage_light
                    name: Garage Lights
              - type: vertical-stack
                cards:
                  - type: entities
                    title: Hose Timer (Rain Seer)
                    entities:
                      - entity: switch.backyard_hose_timer_zone
                        name: Backyard Hose Timer
                      - entity: switch.backyard_hose_timer_rain_delay
                        name: Backyard Hose Timer Rain Delay
                      - entity: switch.backyard_hose_timer_sunset_program
                        name: Backyard Hose Timer Sunset Program
                      - entity: sensor.backyard_hose_timer_battery_level
                        name: Backyard Hose Timer Battery Level
                      - entity: switch.frontyard_hose_timer_zone
                        name: Frontyard Hose Timer
                      - entity: switch.frontyard_hose_timer_rain_delay
                        name: Frontyard Hose Timer Rain Delay
                      - entity: switch.frontyard_hose_timer_sunset_program
                        name: Frontyard Hose Timer Sunset Program
                      - entity: switch.frontyard_hose_timer_smart_watering_program
                        name: Frontyard Hose Timer Smart Watering Program
                      - entity: sensor.frontyard_hose_timer_battery_level
                        name: Frontyard Hose Timer Battery Level
                  - type: gauge
                    entity: sensor.travel_time_to_st_david_s
                    severity:
                      green: 16
                      yellow: 20
                      red: 30
                    min: 0
                    max: 40
                    name: Travel Time To St. David's Hospital
                    needle: false
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - entity: weather.home
                    type: weather-forecast
                  - type: map
                    entities:
                      - entity: device_tracker.sean_hindss_iphone_4
                      - entity: person.amy
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: entities
                        entities:
                          - entity: humidifier.sala_de_estar
                          - entity: fan.sala_de_estar_fan
                          - entity: binary_sensor.sala_de_estar_replace_filter
                          - entity: binary_sensor.sala_de_estar_tank_full
                          - entity: sensor.sala_de_estar_temperature
                          - entity: sensor.sala_de_estar_water_level
                  - type: humidifier
                    entity: humidifier.sala_de_estar

                  - type: thermostat
                    entity: climate.hallway
                  - type: horizontal-stack
                    cards:
                      - type: gauge
                        entity: sensor.canon_ts300_series_black
                        min: 0
                        max: 100
                      - type: gauge
                        entity: sensor.canon_ts300_series_color
                        min: 0
                        max: 100
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - sensor.google_wifi_current_version
                  - sensor.google_wifi_last_restart
                  - sensor.google_wifi_local_ip
                  - sensor.google_wifi_new_version
                  - sensor.google_wifi_status
                  - sensor.google_wifi_uptime
                  - sensor.local_ip
              - type: entities
                entities:
                  - switch.pi_hole
                  - sensor.pi_hole_ads_blocked_today
                  - sensor.pi_hole_dns_queries_cached
                  - sensor.pi_hole_ads_percentage_blocked_today
                  - sensor.pi_hole_seen_clients
                  - sensor.pi_hole_domains_blocked
                  - sensor.pi_hole_dns_unique_domains
                  - sensor.pi_hole_dns_unique_clients
                  - sensor.pi_hole_dns_queries_today
                  - sensor.pi_hole_dns_queries_forwarded
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: history-graph
                    entities:
                      - entity: light.driveway_light
                        name: Driveway Light
                      - entity: binary_sensor.driveway_motion_sensor_occupancy
                        name: Driveway Motion Sensor Occupancy
                      - entity: light.garage_light
                        name: Garage Light
                      - entity: switch.smart_plug_0_switch
                        name: Bedroom String Lights
                      - entity: switch.0x00124b0022d5f06b
                      - entity: binary_sensor.back_door_sensor_contact
                        name: Back Door
                      - entity: binary_sensor.backyard_front_gate_sensor_contact
                        name: Front Gate
          - type: horizontal-stack
            cards:
              - entity: light.hue_white_lamp_1
                type: light
              - type: entities
                entities:
                  - entity: vacuum.deborah
                  - entity: vacuum.darthy
          - type: horizontal-stack
            cards:
              - type: media-control
                entity: media_player.shield
              - type: media-control
                entity: media_player.plex_plex_web_chrome
              - type: entities
                entities:
                  - sensor.plex_openmediavault
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: device_tracker.sean_hindss_iphone_4
                  - entity: sensor.sean_hindss_iphone_activity
                  - entity: sensor.sean_hindss_iphone_average_active_pace
                  - entity: sensor.sean_hindss_iphone_battery_level_3
                  - entity: sensor.sean_hindss_iphone_battery_state_4
                  - entity: sensor.sean_hindss_iphone_bssid_3
                  - entity: sensor.sean_hindss_iphone_connection_type_3
                  - entity: sensor.sean_hindss_iphone_distance
                  - entity: sensor.sean_hindss_iphone_geocoded_location_3
                  - entity: sensor.sean_hindss_iphone_last_update_trigger_3
                  - entity: sensor.sean_hindss_iphone_sim_1_3
                  - entity: sensor.sean_hindss_iphone_sim_2_2
                  - entity: sensor.sean_hindss_iphone_ssid_3
                  - entity: sensor.sean_hindss_iphone_steps
                  - entity: sensor.sean_hindss_iphone_storage_3
                  - entity: device_tracker.apple_watch_de_sean
                  - entity: sensor.apple_watch_de_sean_battery_state
              - type: entities
                entities:
                  - sensor.canon_ts300_series
                  - sensor.canon_ts300_series_black
                  - sensor.canon_ts300_series_color
              - entities:
                  - entity: sensor.r6220_gateway_kib_s_received
                  - entity: sensor.r6220_gateway_kib_s_sent
                hours_to_show: 168
                refresh_interval: 0
                title: NetGear Router Traffic
                type: history-graph
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: entities
                    entities:
                      - entity: sensor.back_door_sensor_battery
                      - entity: sensor.lumi_lumi_sensor_switch_power
                      - entity: sensor.tz3000_vp6clf9d_ts0044_power
                  - type: entities
                    entities:
                      - water_heater.electric_water_heater
                      - sensor.electric_water_heater_alert_count
                      - sensor.electric_water_heater_available_hot_water
                      - sensor.electric_water_heater_override_status
                      - sensor.electric_water_heater_power_usage_today
                      - binary_sensor.electric_water_heater_running
                      - sensor.electric_water_heater_running_state
                      - binary_sensor.electric_water_heater_shutoff_valve
                      - sensor.electric_water_heater_tank_health
                      - sensor.electric_water_heater_water_usage_today
                      - sensor.electric_water_heater_wifi_signal
              - type: history-graph
                entities:
                  - entity: sensor.electric_water_heater_available_hot_water
                  - entity: sensor.electric_water_heater_power_usage_today
                hours_to_show: 168
                refresh_interval: 1
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - fan.levoit_smart_true_hepa_air_purifier
                  - sensor.levoit_smart_true_hepa_air_purifier_filter_life
                  - sensor.levoit_smart_true_hepa_air_purifier_pm2_5
                  - sensor.levoit_smart_true_hepa_air_purifier_air_quality
          - type: horizontal-stack
            cards:
              - type: history-graph
                entities:
                  - entity: sensor.hallway_temperature
                  - entity: sensor.outdoor_temperature_f
                    name: Outdoor Temperature
                  - entity: sensor.hallway_humidity
                  - entity: sensor.midea_dehumidifier_147334558156779_humidity
                hours_to_show: 168
                refresh_interval: 0
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.hallway_humidity
                  - entity: sensor.hallway_temperature
              - type: entities
                entities:
                  - sensor.onhub_b_received_2
                  - sensor.onhub_b_sent_2
                  - sensor.onhub_kib_s_received_2
                  - sensor.onhub_kib_s_sent_2
                  - sensor.onhub_packets_received_2
                  - sensor.onhub_packets_sent_2
                  - sensor.onhub_packets_s_received_2
                  - sensor.onhub_packets_s_sent_2
              - type: history-graph
                entities:
                  - entity: sensor.onhub_packets_s_received_2
                  - entity: sensor.onhub_packets_s_sent_2
          - type: horizontal-stack
            cards:
              - type: history-graph
                entities:
                  - entity: media_player.shield
                    name: NVIDIA shield TV
                  - entity: sensor.apple_watch_de_sean_battery_state
                    name: Sean Hinds' iPhone Battery State
                  - entity: binary_sensor.pi_hole_2
                    name: Pi-hole 2
                  - entity: sensor.google_wifi_status
                    name: Google Fiber Wifi
                  - entity: binary_sensor.pi_hole
                    name: Pi-hole
                  - entity: sensor.pi_hole_dns_unique_clients_2
                    name: Pi-hole Unique DNS Clients
                  - entity: sensor.sean_hindss_iphone_battery_level_3
                    name: Sean Hinds' iPhone Battery Level
                  - entity: sensor.pi_hole_dns_queries_cached_2
                    name: Pi-hole DNS Queries Cached
                  - entity: sensor.pi_hole_dns_queries_today_2
                    name: Pi-hole DNS Queries Today
                  - entity: sensor.pi_hole_dns_unique_domains_2c
                    name: Pi-hole DNS Unique Domains
                title: Home
          - type: horizontal-stack
            cards:
              - entities:
                  - zwave.z_wave_sigma_designs_uzb_z_wave_usb_adapter
                type: entities
