---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "LAN Services Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  - name: "Toby"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"

# TODO: use external WAN endpoints where possible?

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "Pi-hole"
        logo: "assets/tools/pi-hole.png"
        subtitle: "DNS & Ad-blocker"
        tag: "app"
        url: "https://pi.hole/admin/"
        target: "_blank" # optional html a tag target attribute
      - name: "WireGuard"
        logo: "assets/tools/wireguard.png"
        subtitle: "VPN"
        tag: "app"
        url: "http://192.168.1.243:51821"
        target: "_blank" # optional html a tag target attribute
      - name: "NetGear Router"
        logo: "assets/tools/router.png"
        subtitle: "Subnetwork"
        tag: "app"
        url: "http://routerlogin.net"
        target: "_blank" # optional html a tag target attribute
  - name: "Home Automation"
    icon: "fas fa-house"
    items:
      - name: "Home Assistant"
        logo: "assets/tools/hass.png"
        subtitle: "Automation Hub"
        tag: "app"
        url: "http://home.assistant"
  - name: "Container Management"
    icon: "fas fa-box"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Container management"
        tag: "app"
        url: "http://portainer"
      - name: "Kubernetes Dashboard"
        logo: "assets/tools/k8s.png"
        subtitle: "Cluster management"
        tag: "app"
        url: "https://pc0"
  - name: "Devices"
    icon: "fas fa-print"
    items:
      - name: "Canon TS302"
        logo: "assets/tools/canon.png"
        subtitle: "Printer"
        url: "http://canon.local/rui/index.html"
  - name: "NAS"
    icon: "fas fa-box"
    items:
      - name: "Openmediavault"
        logo: "assets/tools/openmediavault.png"
        subtitle: "NAS"
        url: "http://openmediavault.local"
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Document Cloud"
        url: "http://nextcloud"
  - name: "Media"
    icon: "fas fa-play"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media Server"
        url: "http://plex"
      - name: "Paperless"
        logo: "assets/tools/paperless.png"
        subtitle: "Document Manager"
        url: "http://paperless-ng/dashboard"
      - name: "Calibre"
        logo: "assets/tools/calibre.png"
        subtitle: "EBook Manager"
        url: "http://calibre-web"
  - name: "Monitoring"
    icon: "fas fa-desktop"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Monitoring"
        tag: "app"
        url: "http://grafana"
      - name: "Prometheus"
        logo: "assets/tools/prometheus.png"
        subtitle: "Monitoring"
        tag: "app"
        url: "http://prometheus"
  - name: "Database"
    icon: "fas fa-database"
    items:
      - name: "RedisInsight"
        logo: "assets/tools/redis.png"
        subtitle: "Database"
        url: "http://192.168.1.245:8002"
  

