---
version: "2.1"
services:
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
      - WG_HOST=sth144.duckdns.org
      - WG_DEFAULT_DNS=192.168.1.240
    env_file:
      - .env.PASSWORD
    volumes:
      - /home/pi/Volumes/wireguard/etc:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
